modLoader="javafml"
loaderVersion="[41,42)" 
license="Apache License 2.0"
[[mods]]
modId="amethysttoolsmod" 
version="1.19-1.5.0" 
displayName="ยง5Amethyst Tools Mod"
logoFile="amethysttoolsmod-logo.png"
authors="ยง5Macarons Team (Kitoglav, Muffch)"
description="Use amethyst to upgrade your equipment!"
displayURL="https://www.curseforge.com/minecraft/mc-mods/amethyst-tools-mod"
issueURL="https://github.com/Kitoglav/Amethyst-Tools-Mod/issues"
updateJSONURL="https://pastebin.com/raw/g8rHZeHD"
[[dependencies.amethysttoolsmod]]
    modId="forge"
    mandatory=true
    versionRange="[41,42)"
    ordering="NONE"
    side="BOTH"
[[dependencies.amethysttoolsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"